-- Lista de alunas da Imersao, usada como destinatario "imersao" na aba Disparo do admin.
-- Tabela propria de proposito: NAO mistura com a base de creators.
-- ativo = false -> continua salva mas nao recebe disparo.
create table if not exists public.imersao_alunas (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  email      text not null unique,
  whatsapp   text,
  obs        text,
  ativo      boolean not null default true,
  created_at timestamptz not null default now()
);
comment on table public.imersao_alunas is 'Alunas da Imersao. Lista de disparo "imersao" no admin. ativo=false nao recebe email.';
create index if not exists imersao_alunas_ativo_idx on public.imersao_alunas (ativo);

-- So admin logado le/escreve. Anonimo nao enxerga (sao emails de alunas pagantes).
alter table public.imersao_alunas enable row level security;
drop policy if exists "imersao_alunas admin" on public.imersao_alunas;
create policy "imersao_alunas admin" on public.imersao_alunas
  for all to authenticated using (true) with check (true);

-- Os 44 contatos foram inseridos em 11/07/2026 (turma da Imersao Portfolio).
-- Para adicionar mais:
--   insert into public.imersao_alunas (nome, email, whatsapp) values ('Nome', 'email@x.com', '+5511999999999')
--   on conflict (email) do nothing;
